
# --- !Ups

create table "author" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null
);

create table "member" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null
);

create table "book" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "publish_date" date NOT NULL,
  "member_id" bigint(20) NULL,
  FOREIGN KEY ("member_id") REFERENCES member(id)
);

create table "author_book" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "author_id" bigint(20) NOT NULL,
  "book_id" bigint(20) NOT NULL,
  FOREIGN KEY ("author_id") REFERENCES author(id),
  FOREIGN KEY ("book_id") REFERENCES book(id)
);



# --- !Downs

drop table "author_book" if exists;
drop table "author" if exists;
drop table "book" if exists;
drop table "member" if exists;
